### ISSUE TITLE
MQTT v5 Feedbacks

### ISSUE THREAD

**Issue by robertsLando** [mqttjs/MQTT.js#1639]
Use this issue to report your feedback about MQTTv5 version. Positive feedbacks are welcome too so we know everything is working as expected 😄

**Comment by nosovk** [comment]
https://bundlephobia.com/package/mqtt@beta seems two times larger than https://bundlephobia.com/package/mqtt@4 :(

**Comment by nosovk** [comment]
> From [readable-stream](https://github.com/nodejs/readable-stream#readable-stream) docs:
> 
> > If you want to guarantee a stable streams base, regardless of what version of Node you, or the users of your libraries are using, use readable-stream only and avoid the "stream" module in Node-core, for background see [this blogpost](http://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html).
> 
> I'm not sure we can drop it so easily...

that was far-far away. Not relevant to node 14+

**Comment by robertsLando** [comment]
@nosovk Replacing readable-stream with nodejs stream would break browsers. Asked that directly to the readable-stream maintainer

**Comment by nosovk** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream in browser
https://nodejs.org/api/webstreams.html in nodejs

**Comment by robertsLando** [comment]
Would you mind to submit a PR to try that? 

IMO we could create a stream.ts file where, based on the env, we export the apis for both. This would be the cleaner approach

**Comment by nosovk** [comment]
Sorry, but I'm shifted to https://github.com/shanewholloway/js-u8-mqtt in production and currently not using mqtt.js.
In my opinion problem with mqtt.js not in TS, but in obsolete realization (like streams above). Honestly say I think that everything except mqtt-packet is to complex to maintain without total rewrite.

**Comment by rodrigobrochado** [comment]
Thanks for your effort @robertsLando. 

The `vNext` was taken as the solution to many bugs in the past. The "less ambition way" approach adopted by the Microsoft team (#1541) brought some blur on the level of the rework that would come on v5. Besides the release notes of what was done, can you tell us the main points still missing for the rework completion? That could give MQTT.js users like me an idea of how far we are from a more stable and future-proven library. 

Thanks!

**Comment by VirensCn** [comment]
![image](https://github.com/mqttjs/MQTT.js/assets/9736815/9f6f6df0-940b-4879-b546-0f530431cfad)

if use `import * as mqtt from 'mqtt/dist/mqtt';`, has error:
![image](https://github.com/mqttjs/MQTT.js/assets/9736815/4aeaf3bc-31bc-49bd-8c51-fe4ee687dc26)

if use `import mqtt from 'mqtt';`, has error:
![image](https://github.com/mqttjs/MQTT.js/assets/9736815/1fccd735-648e-4e1a-ab1c-27bca3157e0f)
![image](https://github.com/mqttjs/MQTT.js/assets/9736815/2e711978-0e48-4a39-9d4f-4e9a0bb03b75)

**Comment by robertsLando** [comment]
@rodrigobrochado Just to be clear, I don't work for Microsoft, I'm just a MQTTjs users that would like to help.

With v5 my plan is to close as many open PR/issues as possible, fix all tests making them more reliable (also added browser tests to ci that never worked), refactor the code to make it more readable (with TS and other fixes). In general the goal was to keep everything back compatible but making the code easier to work with

Now that v5 is out I will wait to get some users feedback, fix some bugs and then work at v6 that will have more breaking changes. I don't have a specific plan right now but I'm discussing about the changes in some open issues like:

https://github.com/mqttjs/MQTT.js/issues/1648
https://github.com/mqttjs/MQTT.js/issues/1634

If someone wants to share their thoughts I'm open to ideas about how to improve this library in next versions

**Comment by robertsLando** [comment]
@VirensCn It should be:

```
import * as mqtt from 'mqtt/dist/mqtt.min';
```

About the error with `process`, I think you are using `webpack` to bundle your application, in that case webpack v5 has some breaking changes that don't automatically include node polifilly, I generally use this solution :https://stackoverflow.com/a/65556946

Anyway we could also mitigate that error on our side by checking process exists. Let me try to create a PR for this

**Comment by VirensCn** [comment]
The same error occurred when using `import * as mqtt from 'mqtt/dist/mqtt.min';`

I am using vite+vue

**Comment by robertsLando** [comment]
See : https://github.com/vitejs/vite/issues/1973#issuecomment-787571499

**Comment by Eddy-Ko** [comment]
I got error in Console.
```
client.ts:48 Uncaught ReferenceError: global is not defined
    at node_modules/mqtt/build/src/lib/client.js (client.ts:48:2)
    at __require (chunk-ROME4SDB.js?v=8e06f225:11:50)
    at node_modules/mqtt/build/src/mqtt.js (mqtt.ts:8:1)
    at __require (chunk-ROME4SDB.js?v=8e06f225:11:50)
    at mqtt.ts:26:21
```

Here is my package.json.
```
{
  "name": "basketball_admin",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview",
    "type-check": "tsc --noEmit",
    "lint": "eslint --fix --ext .js,.jsx,.ts,.tsx ./src",
    "format": "prettier --write ./src"
  },
  "dependencies": {
    "mqtt": "^5.0.0",
    "ra-data-django-rest-framework": "^0.2.1",
    "react": "^18.2.0",
    "react-admin": "^4.12.1",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20.4.2",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.44.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^3.0.0",
    "typescript": "^5.1.6",
    "vite": "^4.4.3"
  }
}
```
And here is my code.
```
import { useEffect } from "react";
import { connect } from "mqtt";

const MyComponent = () => {
  useEffect(() => {
    const client = connect("mqtt://localhost");
    return () => {
      client.end();
    };
  });
  return <></>;
};
```

**Comment by dvkam** [comment]
@Eddy-Ko about the `global is not defined` error, Webpack v5 does not add automatially anymore polyfills for nodejs builtins. The same accounts for Vite too, global is a node builtin.

You will need to add a polyfill for global.

Take a look at this two discussions, there are solutions mentioned in there:
https://github.com/vitejs/vite/issues/2618 & https://github.com/vitejs/vite/discussions/5912

**Comment by robertsLando** [comment]
@Eddy-Ko check: https://github.com/react-simple-code-editor/react-simple-code-editor/issues/86#issuecomment-1450137826

**Comment by Eddy-Ko** [comment]
> @Eddy-Ko check: [react-simple-code-editor/react-simple-code-editor#86 (comment)](https://github.com/react-simple-code-editor/react-simple-code-editor/issues/86#issuecomment-1450137826)

After using [zirkelc's solution](https://github.com/react-simple-code-editor/react-simple-code-editor/issues/86#issuecomment-1450137826), I received an error stating `Buffer is not defined`. I then attempted [doc-han's solution](https://github.com/mqttjs/MQTT.js/issues/1412#issuecomment-1193363330), but got the error `[plugin:vite:import-analysis] Failed to resolve import "mqtt/dist/mqtt" from "src/mqtt/MyComponent.tsx". Does the file exist?`. I end up using [precompiled-mqtt](https://github.com/ashiqdey/precompiled-mqtt), which worked for my use case.

**Comment by robertsLando** [comment]
@Eddy-Ko 

> [plugin:vite:import-analysis] Failed to resolve import "mqtt/dist/mqtt" from "src/mqtt/MyComponent.tsx".

`import * as mqtt from "mqtt/dist/mqtt.min"`

**Comment by robertsLando** [comment]
I'm not sure if all problems here can be fixed with some changes to the source code of MQTTjs. My feel is that it's just a matter of using the right configuration for each bundler (webpack, vite or whatelse). If someone ends up with a clear solution feel free to write it here or even better open a PR to fix actual docs:

https://github.com/mqttjs/MQTT.js#browser

**Comment by robertsLando** [comment]
@Eddy-Ko I have fixed vite setup docs: https://github.com/mqttjs/MQTT.js#vite

And also created a vite example here: https://github.com/mqttjs/MQTT.js/tree/main/examples/vite-example

**Comment by VirensCn** [comment]
Thank you for your hard work

**Comment by Eddy-Ko** [comment]
> @Eddy-Ko @VirensCn I have fixed vite setup docs: https://github.com/mqttjs/MQTT.js#vite
> 
> And also created a vite example here: https://github.com/mqttjs/MQTT.js/tree/main/examples/vite-example
> 
> Please check them out and let me know.

After trying the Vite setup in the documentation, I encountered a warning:
```
Module "url" has been externalized for browser compatibility. Cannot access "url.parse" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```
This resulted in an error:
```
Uncaught TypeError: url_1.default.parse is not a function
```
Then I found the solution in [this article](https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2).

### My Final Solution
Install these package:
```
yarn add --dev @esbuild-plugins/node-globals-polyfill
yarn add --dev @esbuild-plugins/node-modules-polyfill
```

In vite.config.js:
```javascript
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import { NodeModulesPolyfillPlugin } from "@esbuild-plugins/node-modules-polyfill";

export default defineConfig({
  // Other rules...
  resolve: {
    alias: {
      url: "rollup-plugin-node-polyfills/polyfills/url",
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
        NodeModulesPolyfillPlugin(),
      ],
    },
  },
});
```

**Comment by robertsLando** [comment]
@Eddy-Ko I don't need that additional module. Could you show me how you initialize your client?

**Comment by Eddy-Ko** [comment]
@robertsLando 
You're correct, this was how I initialize the client.
```javascript
const client = mqtt.connect("ws://localhost:8083");
```
By passing an object instead of a string, I no longer need to install the "@esbuild-plugins/node-modules-polyfill" package. While the warning `Module 'util' has been externalized for browser compatibility.` persists, everything runs smoothly. However, "rollup-plugin-polyfill-node" is still required for the `vite build` to function properly.

**Comment by robertsLando** [comment]
@Eddy-Ko what I don't understand is why in my vite example here: https://github.com/mqttjs/MQTT.js/tree/main/examples/vite-example

I don't have to add that, I also don't get any error on `build` or `dev` commands. Could you also check your vite version matches the one in the example?

**Comment by robertsLando** [comment]
By adding: 

```
 resolve: {
    alias: {
      util: "util/",
    }
  },
```

I have been able to also suppress the warning about the util module.


Full configuration:

```
export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
      util: "util/",
    }
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: 'globalThis'
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true
        })
      ]
    }
  }
})
```

**Comment by Eddy-Ko** [comment]
@robertsLando 
Strange, I ran into some issues when trying to run `npm run dev` in your Vite example. Specifically, I got two warnings and an error:
```
Module "util" has been externalized for browser compatibility. Cannot access "util.inspect" in client code.
```
```
Module "url" has been externalized for browser compatibility. Cannot access "url.parse" in client code.
```
```
Uncaught TypeError: url_1.default.parse is not a function
```
Additionally, when running `npm run preview`, I got the following error:
```
Uncaught ReferenceError: process is not defined
```
My node version: `v18.16.0` and npm version: `9.5.1`

**Comment by robertsLando** [comment]
Vite version?

**Comment by VirensCn** [comment]
hello,,Can you try deploying after building?
1. `npm run build `
2. `npm run serve`

![image](https://github.com/mqttjs/MQTT.js/assets/9736815/dcf0a46d-100a-4f9b-b3d6-2a9fd1955978)

**Comment by Eddy-Ko** [comment]
> Vite version?

Vite version in my project: `^4.4.3`
In your vite-example: `^4.4.6`

**Comment by robertsLando** [comment]
Ok I confirm I can reproduce the error when doing: 

```
npm run build && npm run preview
```

Let me dig into this...

**Comment by robertsLando** [comment]
Ok I confirm that for now the only way to make it work also on production is to use the configuration you suggested:

```js
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import { NodeModulesPolyfillPlugin } from "@esbuild-plugins/node-modules-polyfill";
import nodePolyfills from "rollup-plugin-polyfill-node";

export default defineConfig({
  // Other rules...
  resolve: {
    alias: {
      url: "rollup-plugin-node-polyfills/polyfills/url",
      util: "rollup-plugin-node-polyfills/polyfills/util",
      querystring: "rollup-plugin-node-polyfills/polyfills/qs",
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
        NodeModulesPolyfillPlugin(),
      ],
    },
  },
  build: {
    rollupOptions: {
      // Enable rollup polyfills plugin
      // used during production bundling
      plugins: [nodePolyfills()],
    },
  },
});
```

This requires to install: 

```
npm install -D @esbuild-plugins/node-globals-polyfill @esbuild-plugins/node-modules-polyfill rollup-plugin-polyfill-node
```

I will see if this can be improved in future but for now I cannot find alternatives. Reason seems to be that esbuild is used for development and rollup for production build so that's why the previous setup isn't working on produciton

**Comment by Eddy-Ko** [comment]
> A possible solution to this would be to provide a pre-compiled mqttjs version that is already polyfilled and optimized for browser. This is something I tried to archieve in this PR but I'm actually stuck: #1632

Maybe this package can help: [precompiled-mqtt](https://github.com/ashiqdey/precompiled-mqtt)

**Comment by bmacher** [comment]
Hi, I get the following error after updating to v5:

```
node_modules/mqtt/build/src/lib/client.d.ts:5:31 - error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/VWRTVRP/work/github/sdc-production/evo-viu-connector/node_modules/mqtt/node_modules/readable-stream/lib/ours/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/readable-stream` if it exists or add a new declaration (.d.ts) file containing `declare module 'readable-stream';`

5 import { DuplexOptions } from 'readable-stream';
                                ~~~~~~~~~~~~~~~~~

node_modules/mqtt/build/src/lib/store.d.ts:1:26 - error TS7016: Could not find a declaration file for module 'readable-stream'. '/Users/VWRTVRP/work/github/sdc-production/evo-viu-connector/node_modules/mqtt/node_modules/readable-stream/lib/ours/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/readable-stream` if it exists or add a new declaration (.d.ts) file containing `declare module 'readable-stream';`

1 import { Readable } from 'readable-stream';
```

**Comment by robertsLando** [comment]
It's already declared in types and I cannot reproduce that. Could you give me some more context?

**Comment by bmacher** [comment]
> It's already declared in types and I cannot reproduce that. Could you give me some more context?

Okay, I freshly checked out the repo and now it works. I'm sorry for the inconvenience.

**Comment by dvkam** [comment]
Hey @robertsLando may I show you my approach how to resolve the `Buffer`, `process` etc is not defined?
This does not require to install aditionall plugins like `rollup-plugin-polyfill-node`.
My Vite config and the steps:


> 1. Run `npm install buffer stream-browserify util events process` //depending on what you need of course
>
> 2. Then create a new file `nodeSpecific.ts` in the src folder of the project and add:
> ```js
> import { Buffer } from 'buffer'
>
> globalThis.Buffer = Buffer
> ```
>
> 3. Then open the `index.html` file and add the following script in the body. 
> It should look like this:
>
> ```js
> <body>
>   <div id="root"></div>
>    <script type="module" src="/src/nodeSpecific.ts"></script> //add this line
>    <script type="module" src="/src/main.tsx"></script>
> </body>
> ```
>
> 4. Finally open the `vite.config.ts` file and add the `resolve` part:
>
> ```js
> import { defineConfig } from 'vite'
> import react from '@vitejs/plugin-react-swc'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   define: {
>     global: {},
>   },
>   plugins: [react()],
>   resolve: {
>     alias: {
>       buffer: 'buffer',
>       stream: 'stream-browserify',
>       os: 'os-browserify/browser',
>       util: 'util',
>       process: 'process/browser',
>     },
>   },
> })
> ```
>

Also if there are other/better solutions, I am curious to see them.
I did not test thoroughly with MQTT yet but usually this works for me.

**Comment by VirensCn** [comment]
Non urgent issues

If you use Uniapp (vue3+vite) and package it into a WeChat mini program, it will cause a call to `requireBrowser`, resulting in an error exception. The main reason is the `process` variable, which is determined to be a call to this function by the browser environment


![image](https://github.com/mqttjs/MQTT.js/assets/9736815/d97904b9-0ca7-405d-bca6-720fd64e6157)

**Comment by robertsLando** [comment]
> Hey @robertsLando may I show you my approach how to resolve the Buffer, process etc is not defined?

That's exactly what rollup polifilly module does

**Comment by kood-2008** [comment]
> > > @Eddy-Ko @VirensCn I have fixed vite setup docs:  我有固定的 vite 安装文档: [https://github.com/mqttjs/MQTT.js#viteHttps://github.com/mqttjs/mqtt.js#vite](https://github.com/mqttjs/MQTT.js#vite)
> > > And also created a vite example here: 
> > > 并且在这里创造了一个生动的例子: [https://github.com/mqttjs/MQTT.js/tree/main/examples/vite-exampleHttps://github.com/mqttjs/mqtt.js/tree/main/examples/vite-example](https://github.com/mqttjs/MQTT.js/tree/main/examples/vite-example)
> > > Please check them out and let me know.
> > > 请检查一下，然后告诉我。
> > 
> > 
> > After trying the Vite setup in the documentation, I encountered a warning:在尝试了文档中的 Vite 设置之后，我遇到了一个警告:
> > ```
> > Module "url" has been externalized for browser compatibility. Cannot access "url.parse" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This resulted in an error:这导致了一个错误:
> > ```
> > Uncaught TypeError: url_1.default.parse is not a function
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I found the solution in [this article](https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2).然后我在这篇文章中找到了解决方案。
> > ### My Final Solution### 我的最终解决方案
> > Install these package:安装以下软件包:
> > ```
> > yarn add --dev @esbuild-plugins/node-globals-polyfill
> > yarn add --dev @esbuild-plugins/node-modules-polyfill
> > yarn add --dev rollup-plugin-polyfill-node
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In vite.config.js:在 vite.config.js 中:
> > ```js
> > import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
> > import { NodeModulesPolyfillPlugin } from "@esbuild-plugins/node-modules-polyfill";
> > import nodePolyfills from "rollup-plugin-polyfill-node";
> > 
> > export default defineConfig({
> >   // Other rules...
> >   resolve: {
> >     alias: {
> >       url: "rollup-plugin-node-polyfills/polyfills/url",
> >       util: "rollup-plugin-node-polyfills/polyfills/util",
> >       querystring: "rollup-plugin-node-polyfills/polyfills/qs",
> >     },
> >   },
> >   optimizeDeps: {
> >     esbuildOptions: {
> >       // Node.js global to browser globalThis
> >       define: {
> >         global: "globalThis",
> >       },
> >       // Enable esbuild polyfill plugins
> >       plugins: [
> >         NodeGlobalsPolyfillPlugin({
> >           buffer: true,
> >         }),
> >         NodeModulesPolyfillPlugin(),
> >       ],
> >     },
> >   },
> >   build: {
> >     rollupOptions: {
> >       // Enable rollup polyfills plugin
> >       // used during production bundling
> >       plugins: [nodePolyfills()],
> >     },
> >   },
> > });
> > ```
> 
> useful for me ,mqtt5.0.2 vite4.3.9
> 
> 对我很有用，mqtt5.0.2 vite4.3.9

when i  yarn build,  This resulted in an error:, 
error during build:
RollupError: "toASCII" is not exported by "__vite-browser-external", imported by "node_modules/rollup-plugin-node-polyfills/polyfills/url.js

it seemlike  this code in vite.coinfig.ts:      
alias: {
          '@': pathResolve('./src'),
          url: "rollup-plugin-node-polyfills/polyfills/url",  // here
          util: "rollup-plugin-node-polyfills/polyfills/util",
          querystring: "rollup-plugin-node-polyfills/polyfills/qs",
      }
What should I do

**Comment by robertsLando** [comment]
@kood-2008 Refer to this: https://github.com/mqttjs/MQTT.js/blob/main/examples/vite-example/vite.config.js

**Comment by kood-2008** [comment]
> @kood-2008 Refer to this: https://github.com/mqttjs/MQTT.js/blob/main/examples/vite-example/vite.config.js
> 
> @ kood-2008参考此 https://github.com/mqttjs/mqtt.js/blob/main/examples/vite-example/vite.config.js :

Hello, I successfully used mqtt for the Yarn dev project after using the vite.config.ts code you provided. However, the project will report an error after Yarn build And deploy it to run on the server, so I git clone your project and install example project(Folder vite-example). unfortunate, npm run dev succeeded, but npm run build failed after deploy it to run on the server

error Code:   UR.default.parse is not a functionat Object.Up [as connect]
click in:  
...
function Up(t, e) {
    if (cc("connecting to an MQTT broker..."),
    typeof t == "object" && !e && (e = t,
    t = ""),
    e = e || {},
    t && typeof t == "string") {
        const i = UR.default.parse(t, !0);   //  <------------------------------------  error code  Looks like it's from here
        if (i.port != null && (i.port = Number(i.port)),
        e = Object.assign(Object.assign({}, i), e),
        e.protocol === null)
            throw new Error("Missing protocol");
        e.protocol = e.protocol.replace(/:$/, "")
    }
    if (HR(e),
.....

**Comment by robertsLando** [comment]
Try adding the url polifilly:

```
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import { NodeModulesPolyfillPlugin } from "@esbuild-plugins/node-modules-polyfill";
import nodePolyfills from "rollup-plugin-polyfill-node";

export default defineConfig({
  // Other rules...
  resolve: {
    alias: {
      url: "rollup-plugin-node-polyfills/polyfills/url", <-------- THIS
      util: "rollup-plugin-node-polyfills/polyfills/util",
      querystring: "rollup-plugin-node-polyfills/polyfills/qs",
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
        NodeModulesPolyfillPlugin(),
      ],
    },
  },
  build: {
    rollupOptions: {
      // Enable rollup polyfills plugin
      // used during production bundling
      plugins: [nodePolyfills()],
    },
  },
});
```

**Comment by vagreargnatry** [comment]
@robertsLando Hello! I have a request for the `exports` of [package.json](https://github.com/mqttjs/MQTT.js/blob/main/package.json). Please read below.

[This method](https://github.com/mqttjs/MQTT.js/issues/1269#issuecomment-841243295) cannot work in MQTT.js v5 [but works in MQTT.js v4.3.7](https://github.com/mqttjs/MQTT.js/issues/1596#issuecomment-1655819678).

In MQTT.js v5 the error is `[vite] Internal server error: Failed to resolve import "mqtt/dist/mqtt.min" from "{{ component name }}". Does the file exist?`. I think the reason is it cannot find this file because of the `exports` of [package.json](https://github.com/mqttjs/MQTT.js/blob/main/package.json).

Then I add `"./dist/*": "./dist/*.js",` to [the next line here](https://github.com/mqttjs/MQTT.js/blob/main/package.json#L40), then it works.

I don't want to install `@esbuild-plugins/node-globals-polyfill` and `@esbuild-plugins/node-modules-polyfill` and `rollup-plugin-polyfill-node`. Please add `"./dist/*": "./dist/*.js"` or some what to [package.json](https://github.com/mqttjs/MQTT.js/blob/main/package.json).

Please correct me if I am wrong. Thanks for reading!

**Comment by robertsLando** [comment]
@vagreargnatry would you like to submit a PR please?

**Comment by xukaishan** [comment]
You also need to pay attention to the browser environment：
import * as mqtt from 'mqtt/dist/mqtt.min'

**Comment by robertsLando** [comment]
For anyone using mqttjs in browser, just use

```js
import * as mqtt from 'mqtt/dist/mqtt.min'
```

there is no need of any configuration both in vite/webpack then

**Comment by function1983** [comment]
> For anyone using mqttjs in browser, just use
> 
> ```js
> import * as mqtt from 'mqtt/dist/mqtt.min'
> ```
> 
> there is no need of any configuration both in vite/webpack then

Thank you @robertsLando for the instruction. I just want to report my findings:
Environment: @sveltejs/kit 1.25.1 + vite 4.4.11 + mqtt 5.1.0.
vite.config.js just as yours

**DOESN'T WORK:** `import * as mqtt from 'mqtt/dist/mqtt.min'`
> Errors in terminal:
> **npm run dev:** ws does not work in the browser. Browser clients must use the native WebSocket object
> **npm run build:** mqtt.connect is not a function

**WORKS:** `import * as mqtt from 'mqtt'`
> Both dev and build will work in browser

**Comment by robertsLando** [comment]
@function1983 Remove the `.min`, I corrected my answer above

**Comment by function1983** [comment]
> @function1983 Remove the `.min`, I corrected my answer above. If you use that you don't need all those polifilly on vite config

My thought was exactly the same. But in reality I still do need polyfilling as mentioned in your vite config.
Without polyfilling, `npm run build` would complete normally but when deployed it will return this error message:
> Uncaught (in promise) ReferenceError: process is not defined

Other than that quirk, mqttjs runs flawlessly and very stable for me.

**Comment by robertsLando** [comment]
> My thought was exactly the same. But in reality I still do need polyfilling as mentioned in your vite config.
Without polyfilling, npm run build would complete normally but when deployed it will return this error message:

There must be something else that requires them because in my example I'm able to run it and build too without any polifilly

**Comment by tukusejssirs** [comment]
I have just upgrade to `v5`, I don’t know how to set `setMaxListeners`.

In `v4`, I used `client.setMaxListeners(number)`, however, the property seems not to exist anymore.

Was it moved somewhere else? Was it removed? Does it still needs to be implemented? :thinking: :pray:

**Comment by robertsLando** [comment]
@tukusejssirs `setMaxListeners` should be an EventEmitter method so it should be present as MqttClient extends it, are you using mqtt on nodejs or browser? how do you import it in your code?

**Comment by robertsLando** [comment]
@tukusejssirs 5.1.3 fixes your issue

**Comment by robertsLando** [comment]
I'm closing this as now mqtt v5 is out

**Comment by robertsLando** [comment]
FYI starting from 5.2.1 you can now import mqtt using:

`import mqtt from 'mqtt'`
