### ISSUE TITLE
5.0.3 fails to compile in TS project

### ISSUE THREAD

**Issue by LRagji** [mqttjs/MQTT.js#1673]
I am trying simple thing 
1. NPM install mqtt in a fresh typescript project
2. add import * as mqttClient from 'mqtt'; as suggested by the readme
3. run tsc

It is giving me lot of errors 
1. Missing type definitions for @types/readable-stream and @types/ws
2. Error TS1259 Module '"stream"' can only be default-imported using the 'esModuleInterop' flag for file node_modules/@types/node/stream.d.ts:1425:5 

What am i doing wrong?

**Comment by LRagji** [comment]
I had to add `  "esModuleInterop": true` flag to my tsconfig to make this work not sure how correct is that?

**Comment by VirtualWolf** [comment]
I have the same issue with `tsc` complaining about missing type definitions for `@types/readable-stream` after updating MQTT.js from 4.x to 5.0.3.

I'd run into the same missing type definitions for `@types/ws` a while back too and had added that my project's dev dependencies, looking in the current `package.json` for MQTT.js it looks like it's there but apparently it's... not working or something?
