### ISSUE TITLE
[Bug]: Build error: Could not find a declaration file for module 'ws' in 5.11.1 and beyond - works in 5.11.0

### ISSUE THREAD

**Issue by hjdhjd** [mqttjs/MQTT.js#1991]
### MQTTjs Version

5.12.0

### Broker

N/A

### Environment

NodeJS

### Description

Working in a TypeScript project that's always been fine. Updated the package release from 5.11.0 to 5.12.0. Transpiling yields:

```
node_modules/mqtt/build/lib/client.d.ts:5:31 - error TS7016: Could not find a declaration file for module 'ws'. '/myprojectdir/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

5 import { ClientOptions } from 'ws';
```

### Minimal Reproduction

Admittedly not minimal...but it makes the point. 😄 
 
1.. Download the source: https://github.com/hjdhjd/homebridge-plugin-utils/archive/refs/tags/v1.15.3.tar.gz
2. Update the MQTT package version to 5.11.0.
3. npm run build to verify it works.
4. Update the MQTT package version to 5.11.1 or 5.12.0
5. npm run clean ; npm run build
6. Error above occurs.

### Debug logs

N/A. See above.

**Comment by robertsLando** [comment]
@SmashingQuasar I have a feel that's related to https://github.com/mqttjs/MQTT.js/pull/1986.

Dunno if using `import type ...` could fix this issue but could you check and fix this please?

**Comment by hjdhjd** [comment]
I believe my imports are correct. You're right about the cause being that PR. The type dependency being moved to devDependencies for ws causes an issue because you're importing `ClientOptions` from ws in the type declarations for client.ts (client.d.ts).

TL;DR I think you'll need to do one of:

1. Move `ws` back to being a proper dependency, not just a dev dependency. Arguably, this is the right answer considering you're pulling it in client.ts.
2. Create a specific typing for ClientOptions and export it. Suboptimal because it really should come from `ws`.

On the end user side for consumers of this library, we have two choices as of 5.11.1 onwards:

1. Set `skipLibCheck` to `true` in `tsconfig.json`. Not preferable because this will skip all type checking in declaration files...which is a big part of the reason why people use TypeScript. 😄
2. Add `@types/ws` to the `devDependencies` in my project. This will resolve the issue, but fundamentally - I shouldn't need to do this. MQTT.js is the one making the declaration, I'm just working around it. 😄

Both will address the error, but I would suggest that the typing appropriately come from MQTT.

**Comment by robertsLando** [comment]
I also opened #1992 in case

**Comment by SmashingQuasar** [comment]
@robertsLando 

After quickly looking into it, it seems that this is because you always use hard imports `import { x } from 'something'` which results in all imports being forced as dependencies.
For interfaces such as `ClientOptions`, you should use `import type { ClientOptions } from 'ws'` as this will tell TypeScript to erase this import and its usage at compile time and it won't exist at run time.
This is, in my opinion, the ideal solution as it will avoid having purely development aimed dependencies (`@types/*`) exported to a development environment.

**Comment by robertsLando** [comment]
> or interfaces such as ClientOptions, you should use import type { ClientOptions } from 'ws' as this will tell TypeScript to erase this import and its usage at compile time and it won't exist at run time.

Yeah that was my suspect as stated here: https://github.com/mqttjs/MQTT.js/issues/1991#issuecomment-2851444959

The same issue applies to `readable-stream`

> Edit: There is an ESlint rule that automatically makes all imports used only for types imported as import type which would automatically solve this type of issue in the future.

Could you take care of that in a PR please?

**Comment by SmashingQuasar** [comment]
> > or interfaces such as ClientOptions, you should use import type { ClientOptions } from 'ws' as this will tell TypeScript to erase this import and its usage at compile time and it won't exist at run time.
> 
> Yeah that was my suspect as stated here: [#1991 (comment)](https://github.com/mqttjs/MQTT.js/issues/1991#issuecomment-2851444959)
> 
> The same issue applies to `readable-stream`
> 
> > Edit: There is an ESlint rule that automatically makes all imports used only for types imported as import type which would automatically solve this type of issue in the future.
> 
> Could you take care of that in a PR please?

Yes, I'll do a PR to add this rule and resolve type imports.

**Comment by SmashingQuasar** [comment]
> > [@robertsLando](https://github.com/robertsLando)
> > 
> > After quickly looking into it, it seems that this is because you always use hard imports `import { x } from 'something'` which results in all imports being forced as dependencies. For interfaces such as `ClientOptions`, you should use `import type { ClientOptions } from 'ws'` as this will tell TypeScript to erase this import and its usage at compile time and it won't exist at run time. This is, in my opinion, the ideal solution as it will avoid having purely development aimed dependencies (`@types/*`) exported to a development environment.
> > 
> > Edit: There is an ESlint rule that automatically makes all imports used only for types imported as `import type` which would automatically solve this type of issue in the future.
> 
> Thanks - I learned something there. That’s an elegant solution that I’ll file away for the future. Appreciated!

Any time!

**Comment by hjdhjd** [comment]
Issue unfortunately persists in 5.12.1:

```
Could not find a declaration file for module 'ws'. '/projectdir/node_modules/ws/index.js' implicitly has an 'any' type.

5 import type { ClientOptions } from 'ws';
```

**Comment by SmashingQuasar** [comment]
> Issue unfortunately persists in 5.12.1:
> 
> ```
> Could not find a declaration file for module 'ws'. '/projectdir/node_modules/ws/index.js' implicitly has an 'any' type.
> 
> 5 import type { ClientOptions } from 'ws';
> ```

So I tried to replicate the issue with 5.12.1.

I created a brand new project, with the following code as only file:

```js
import { connect } from "mqtt"; // import connect from mqtt
let client = connect("mqtt://test.mosquitto.org"); // create a client

client.on("connect", () => {
  console.log("Connected to MQTT broker");
  client.subscribe("test/topic", (err) => {
    if (!err) {
      console.log("Subscribed to topic");
    } else {
      console.error("Subscription error:", err);
    }
  });
});
```

I started it raw with Node 22 as a `.mjs` file. It worked without issues.

Then I converted it to a `.mts` file, ran `pnpm exec tsc src/main.mts` and it compiled without issue.
Finally, I ran the compiled file which ran without issue.

I'm struggling to understand how to reproduce your error, could you provide a repository or more information, please?

**Comment by hjdhjd** [comment]
> > Issue unfortunately persists in 5.12.1:
> > ```
> > Could not find a declaration file for module 'ws'. '/projectdir/node_modules/ws/index.js' implicitly has an 'any' type.
> > 
> > 5 import type { ClientOptions } from 'ws';
> > ```
> 
> So I tried to replicate the issue with 5.12.1.
> 
> I created a brand new project, with the following code as only file:
> 
> import { connect } from "mqtt"; // import connect from mqtt
> let client = connect("mqtt://test.mosquitto.org"); // create a client
> 
> client.on("connect", () => {
>   console.log("Connected to MQTT broker");
>   client.subscribe("test/topic", (err) => {
>     if (!err) {
>       console.log("Subscribed to topic");
>     } else {
>       console.error("Subscription error:", err);
>     }
>   });
> });
> I started it raw with Node 22 as a `.mjs` file. It worked without issues.
> 
> Then I converted it to a `.mts` file, ran `pnpm exec tsc src/main.mts` and it compiled without issue. Finally, I ran the compiled file which ran without issue.
> 
> I'm struggling to understand how to reproduce your error, could you provide a repository or more information, please?

Repo in question is the one I referenced in the original report. Interestingly, I cannot recreate the issue when I cleanly clone the repo, and yet in my private tree, I experience the error despite cleaning the environment. I’ll to investigate a bit further on my end what’s going on. Appreciate everyone’s rapid iteration…I’ll followup if I can cleanly recreate the issue.

**Comment by hjdhjd** [comment]
> This should be reopened I think. [@hjdhjd](https://github.com/hjdhjd) did you manage to make it work with a version higher than 5.11.1?
> 
> Related to [#2006](https://github.com/mqttjs/MQTT.js/issues/2006)

I gave up and just added ws as a dependency to solve the issue. Though shifting to importing as a type removed the TS compiler dependency, there still seems to be an actual dependency on ‘ws’ in MQTT somewhere. 

I do think this is still a bug, but I didn’t want to keep poking at it because the developers didn’t seem to want to chase it down further and I can work around the problem.

**Comment by SmashingQuasar** [comment]
> > This should be reopened I think. [@hjdhjd](https://github.com/hjdhjd) did you manage to make it work with a version higher than 5.11.1?
> > Related to [#2006](https://github.com/mqttjs/MQTT.js/issues/2006)
> 
> I gave up and just added ws as a dependency to solve the issue. Though shifting to importing as a type removed the TS compiler dependency, there still seems to be an actual dependency on ‘ws’ in MQTT somewhere.
> 
> I do think this is still a bug, but I didn’t want to keep poking at it because the developers didn’t seem to want to chase it down further and I can work around the problem.

Sorry for not replying on this thread earlier. Since this issue is closed and has not been reopened, and nobody @ me directly, I never received a notification and simply forgot to check. I'm still willing to investigate this indeed. I gave a detailed answer of explaining the problem on #2006 and I am awaiting the preferred solution from the maintainer to go forward with implementation.
