### ISSUE TITLE
setImmediate polyfill is not implementing node 16 standard of setImmediate

### ISSUE THREAD

**Issue by filipomar** [mqttjs/MQTT.js#1474]
While working with the MQTT client on the browser, I noticed callbacks (sent through setImmediate) are missing parameters.

I tracked the problem down to this snippet:

```javascript
const setImmediate = global.setImmediate || function (callback) {
  // works in node v0.8
  nextTick(callback)
}
```

[Here](https://github.com/mqttjs/MQTT.js/blob/main/lib/client.js#L20) is the problematic function mentioned above.

It does not implement the setImmediate as per the documentation [here](https://nodejs.org/dist/latest-v16.x/docs/api/timers.html#setimmediatecallback-args) **with** the callback args.

But using core-js's polyfill is for now a good enough alternative (need to be imported before the mqtt lib):

```
import 'core-js/modules/web.immediate'
```

**Comment by filipomar** [comment]
[PR](https://github.com/mqttjs/MQTT.js/pull/1497) submitted
