### ISSUE TITLE
 Ali Mini Program not work in v4.2.0

### ISSUE THREAD

**Issue by techGay** [mqttjs/MQTT.js#1140]
In PR [#1135](https://github.com/mqttjs/MQTT.js/pull/1135)  change  index.js and add 
```js
 typeof __webpack_require__ === 'function'
```

```js
// eslint-disable-next-line camelcase
if ((typeof process !== 'undefined' && process.title !== 'browser') || typeof __webpack_require__ === 'function') {
  protocols.mqtt = require('./tcp')
  protocols.tcp = require('./tcp')
  protocols.ssl = require('./tls')
  protocols.tls = require('./tls')
  protocols.mqtts = require('./tls')
} else {
  protocols.wx = require('./wx')
  protocols.wxs = require('./wx')

  protocols.ali = require('./ali')
  protocols.alis = require('./ali')
}
```

I found that 
```js
 typeof __webpack_require__ === 'function'
```
in Ali Mini Program is true，so will not go else conditional branch to require correct protocol file(ali.js) than an error occur
```js
TypeError: net.createConnection is not a function
    at Object.streamBuilder (mqtt.js:1737)
    at MqttClient.wrapper [as streamBuilder] (mqtt.js:2388)
    at MqttClient._setupStream (mqtt.js:300)
    at new MqttClient (mqtt.js:279)
    at connect (mqtt.js:2391)
    at Object.doConnect (tasks.js:76)
    at Object.onTap (tasks.js:50)
```

**Comment by YoDaMa** [comment]
release 4.2.1 (#1149) should fix this.

**Comment by YoDaMa** [comment]
apologies unrelated

**Comment by techGay** [comment]
version  v4.2.1 not work well too,the same error occur.
```js
TypeError: net.createConnection is not a function
    at Object.streamBuilder (mqtt.js:1737)
    at MqttClient.wrapper [as streamBuilder] (mqtt.js:2388)
    at MqttClient._setupStream (mqtt.js:300)
    at new MqttClient (mqtt.js:279)
    at connect (mqtt.js:2391)
    at Object.doConnect (tasks.js:76)
    at Object.onTap (tasks.js:50)
```
Now i have to download the source code then remove the codition
```js
typeof __webpack_require__ === 'function'
```
and according to PR #1057 to fix other error,it will work well on real phone.So there any other best way to solve this problem?

**Comment by ZenDay** [comment]
In fact,  at PR #1135 
```js
// eslint-disable-next-line camelcase
if ((typeof process !== 'undefined' && process.title !== 'browser') || typeof __webpack_require__ === 'function') {
  protocols.mqtt = require('./tcp')
  protocols.tcp = require('./tcp')
  protocols.ssl = require('./tls')
  protocols.tls = require('./tls')
  protocols.mqtts = require('./tls')
}
```
the codition here is to judge if `mqtt` is NOT used in browser, because the code at `./tcp` and `./tls` use the nodejs library.

However `typeof __webpack_require__ === 'function'` is to judge if it's used in browser. It will cause all the webpack app which use `mqtt` over v4.2.0(and 4.2.1) throw an TypeError
```
Uncaught TypeError: net.createConnection is not a function
```

Here's the correction:
```js
// eslint-disable-next-line camelcase
if ((typeof process === 'undefined' || process.title !== 'browser') && typeof __webpack_require__ !== 'function') {
  protocols.mqtt = require('./tcp')
  protocols.tcp = require('./tcp')
  protocols.ssl = require('./tls')
  protocols.tls = require('./tls')
  protocols.mqtts = require('./tls')
}
```
Just like the code at the same PR:
```js
// eslint-disable-next-line camelcase
var IS_BROWSER = (typeof process !== 'undefined' && process.title === 'browser') || typeof __webpack_require__ === 'function'
```

**Comment by techGay** [comment]
> In fact, at PR #1135
> 
> ```js
> // eslint-disable-next-line camelcase
> if ((typeof process !== 'undefined' && process.title !== 'browser') || typeof __webpack_require__ === 'function') {
>   protocols.mqtt = require('./tcp')
>   protocols.tcp = require('./tcp')
>   protocols.ssl = require('./tls')
>   protocols.tls = require('./tls')
>   protocols.mqtts = require('./tls')
> }
> ```
> 
> the codition here is to judge if `mqtt` is NOT used in browser, because the code at `./tcp` and `./tls` use the nodejs library.
> 
> However `typeof __webpack_require__ === 'function'` is to judge if it's used in browser. It will cause all the webpack app which use `mqtt` over v4.2.0(and 4.2.1) throw an TypeError
> 
> ```
> Uncaught TypeError: net.createConnection is not a function
> ```
> 
> Here's the correction:
> 
> ```js
> // eslint-disable-next-line camelcase
> if ((typeof process === 'undefined' || process.title !== 'browser') && typeof __webpack_require__ !== 'function') {
>   protocols.mqtt = require('./tcp')
>   protocols.tcp = require('./tcp')
>   protocols.ssl = require('./tls')
>   protocols.tls = require('./tls')
>   protocols.mqtts = require('./tls')
> }
> ```
> 
> Just like the code at the same PR:
> 
> ```js
> // eslint-disable-next-line camelcase
> var IS_BROWSER = (typeof process !== 'undefined' && process.title === 'browser') || typeof __webpack_require__ === 'function'
> ```

yes , you are right
